import {
  ChartData,
  FirebaseChartCompProps,
  FirebaseChartInfo,
} from "@/types/dashboard";
import { useEffect, useState } from "react";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import BarChartComp from "../charts/BarChart";
import EditFirebaseChart from "./EditFirebaseChart";
import DeleteChart from "../DeleteChart";
import PieChartComp from "../charts/PieChart";
import { getRandomColor } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import LineChartComp from "../charts/LineChart";
import { Button } from "@/components/ui/button";
import { AiOutlinePicture } from "react-icons/ai";
import { saveAs } from "file-saver";
import domtoimage from "dom-to-image";
import toast from "react-hot-toast";
import { useRecoilValue } from "recoil";
import { customer_info } from "@/atoms/atoms";
import { DEFAULT_SETTINGS } from "@/constants/constants";

const ChartComp = ({ chart, db, p, sUC }: FirebaseChartCompProps) => {
  const [data, setData] = useState<ChartData[]>([]);
  const [total, setTotal] = useState(0);
  const [visible, setVisible] = useState(false);
  const [capturing, setCapturing] = useState(false);
  const { field, name, pathToCollection, type } =
    chart.chart_info as FirebaseChartInfo;
  const { bar, line } = p.customization || DEFAULT_SETTINGS;
  const customer = useRecoilValue(customer_info);
  const nodeName = name.toLowerCase().split(" ").join("-");

  const handleDownload = async () => {
    const node = document.getElementById(nodeName)!;

    try {
      !customer[0]?.has_access && setVisible(true);
      setCapturing(true);

      const blob = await domtoimage.toBlob(node);
      saveAs(blob, `${name} (${p.project_info.projectName}).png`);
    } catch (e) {
      toast.error("An error occured while exporting the chart.");
    } finally {
      setVisible(false);
      setCapturing(false);
    }
  };

  useEffect(() => {
    const q = query(collection(db, pathToCollection), orderBy(field));
    const unsub = onSnapshot(q, (d) => {
      const t: ChartData[] = [];

      const mapped = d.docs
        .map((a) => a.data())
        .reduce((acc, curr) => {
          acc[curr[field]] ? (acc[curr[field]] += 1) : (acc[curr[field]] = 1);

          return acc;
        }, {});

      for (let i in mapped) {
        t.push({
          field: i,
          value: mapped[i],
          fill:
            type === "pie"
              ? getRandomColor()
              : type === "bar"
              ? bar.color
              : type === "line"
              ? line.color
              : "#ff9100",
        });
      }

      setData(t);
      setTotal(d.docs.length);
    });

    return unsub;
  }, []);

  return (
    <div
      className="w-full border rounded-xl px-4 py-4 pb-3 bg-white"
      id={nodeName}
    >
      <div className="w-full flex items-center justify-between mb-6 gap-2">
        <p className="mr-auto">
          {name} <Badge className="text-white bg-gray-400">{total}</Badge>
        </p>

        {!capturing && (
          <>
            <Button
              className="bg-white font-normal text-black w-fit hover:bg-white/90 border"
              onClick={handleDownload}
            >
              <AiOutlinePicture className="text-lg" />
            </Button>
            <EditFirebaseChart db={db} chart={chart} sUC={sUC} />
            <DeleteChart chart={chart} p={p} sUC={sUC} />{" "}
          </>
        )}
      </div>

      {type === "bar" && (
        <BarChartComp
          data={data}
          total={total}
          customization={p.customization}
        />
      )}

      {type === "pie" && (
        <PieChartComp
          data={data}
          total={total}
          customization={p.customization}
        />
      )}

      {type === "line" && (
        <LineChartComp
          data={data}
          total={total}
          customization={p.customization}
        />
      )}

      {visible && (
        <p className="w-full text-center text-sm mt-2 text-gray-400">
          Chart generated by Ventivo (https://ventivo.co)
        </p>
      )}
    </div>
  );
};

export default ChartComp;
