import FirebaseProjectPage from "@/components/dashboard/firebase-project";
import { Metadata } from "next";

export const generateMetadata = async (props: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> => {
  const { slug } = await props.params;

  return {
    // work on this
    title: "Order ~ Willow",
    description: "Generated by create next app", // Fix this
    openGraph: {
      title: "Order ~ Willow",
      description: "Generated by create next app", // Fix this
      type: "website",
      url: "https://willow.com", // Fix this
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "Order ~ Willow",
      description: "Generated by create next app",
      images: [
        {
          url: "", // Fix this
        },
      ],
    },
  };
};

const Page = async (props: { params: Promise<{ slug: string }> }) => {
  const { slug } = await props.params;

  return <FirebaseProjectPage slug={slug} />;
};

export default Page;
