import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Home ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Home ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.home, // Fix this
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Home ~ Willow",
    description: "Generated by create next app",
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Home = () => {
  redirect(PAGES.login);
};

export default Home;
