import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import ThemeToggle from "@/components/general/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased flex items-center justify-center">
        <Toaster />
        <Suspense>{children}</Suspense>
        <ThemeToggle />
      </body>
    </html>
  );
};

export default RootLayout;
