import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import { Toaster as Sonner } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// <title>{title ? `${title} ~ Ventivo` : "Ventivo"}</title>
// <meta
//   name="description"
//   content="Get realtime charts from your data."
// />
// {/* <!-- Facebook Meta Tags --> */}
// <meta property="og:url" content="https://app.ventivo.co" />
// <meta property="og:type" content="website" />
// <meta property="og:title" content="Ventivo" />
// <meta
//   property="og:description"
//   content="Get realtime charts from your data."
// />
// <meta
//   property="og:image"
//   content="https://app.ventivo.co/og-image.png"
// />
// {/* <!-- Twitter Meta Tags --> */}
// <meta name="twitter:card" content="summary_large_image" />
// <meta property="twitter:domain" content="ventivo.co" />
// <meta property="twitter:url" content="https://app.ventivo.co" />
// <meta name="twitter:title" content="Ventivo" />
// <meta
//   name="twitter:description"
//   content="Get realtime charts from your data."
// />
// <meta
//   name="twitter:image"
//   content="https://app.ventivo.co/og-image.png"
// />

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased flex items-center justify-center dark">
        <Toaster />
        <Sonner />
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
