import {
  ChartData,
  PostgresChartCompProps,
  PostgresChartInfo,
  PostgresProjectInfo,
} from "@/types/dashboard";
import { useEffect, useState } from "react";
import BarChartComp from "../charts/BarChart";
import DeleteChart from "../DeleteChart";
import PieChartComp from "../charts/PieChart";
import { getRandomColor } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import LineChartComp from "../charts/LineChart";
import { Button } from "@/components/ui/button";
import { AiOutlinePicture } from "react-icons/ai";
import { saveAs } from "file-saver";
import domtoimage from "dom-to-image";
import toast from "react-hot-toast";
import { useAtomValue } from "jotai";
import { customer_info } from "@/atoms/atoms";
import { DEFAULT_SETTINGS } from "@/constants/constants";
import EditPostgresChart from "./EditPostgresChart";

const ChartComp = ({ chart, tables, p, sUC }: PostgresChartCompProps) => {
  const [data, setData] = useState<ChartData[]>([]);
  const [total, setTotal] = useState(0);
  const [visible, setVisible] = useState(false);
  const [capturing, setCapturing] = useState(false);
  const { column, table, type, name } = chart.chart_info as PostgresChartInfo;
  const { bar, line } = p.customization || DEFAULT_SETTINGS;
  const customer = useAtomValue(customer_info);
  const nodeName = name.toLowerCase().split(" ").join("-");

  const handleDownload = async () => {
    const node = document.getElementById(nodeName)!;

    try {
      !customer[0]?.has_access && setVisible(true);
      setCapturing(true);

      const blob = await domtoimage.toBlob(node);
      saveAs(blob, `${name} (${p.project_info.projectName}).png`);
    } catch (e) {
      toast.error("An error occured while exporting the chart.");
    } finally {
      setVisible(false);
      setCapturing(false);
    }
  };

  const getData = async (interval: any) => {
    try {
      const res = await fetch(
        `/api/get-column-data?table=${table}&column=${column}`,
        {
          method: "POST",
          body: JSON.stringify(p.project_info),
          headers: { "Content-Type": "application/json" },
        }
      );
      const d = (await res.json()).data.res;
      const t: ChartData[] = [];

      const mapped = d.reduce((acc: any, curr: any) => {
        acc[curr[column]] ? (acc[curr[column]] += 1) : (acc[curr[column]] = 1);

        return acc;
      }, {});

      for (let i in mapped) {
        t.push({
          field: i,
          value: mapped[i],
          fill:
            type === "pie"
              ? getRandomColor()
              : type === "bar"
              ? bar.color
              : type === "line"
              ? line.color
              : "#ff9100",
        });
      }

      setData(t);
      setTotal(d.length);
    } catch (e) {
      toast.error("Error fetching chart data.");
      clearInterval(interval);
    }
  };

  useEffect(() => {
    const interval = setInterval(() => getData(interval), 5000);

    getData(interval);

    return () => clearInterval(interval);
  }, []);

  return (
    <div
      className="w-full border rounded-xl px-4 py-4 pb-3 bg-white"
      id={nodeName}
    >
      <div className="w-full flex items-center justify-between mb-6 gap-2">
        <p className="mr-auto">
          {name} <Badge className="text-white bg-gray-400">{total}</Badge>
        </p>

        {!capturing && (
          <>
            <Button
              className="bg-white font-normal text-black w-fit hover:bg-white/90 border"
              onClick={handleDownload}
            >
              <AiOutlinePicture className="text-lg" />
            </Button>
            <EditPostgresChart
              tables={tables}
              chart={chart}
              sUC={sUC}
              project_info={p.project_info as PostgresProjectInfo}
            />
            <DeleteChart chart={chart} p={p} sUC={sUC} />
          </>
        )}
      </div>

      {type === "bar" && (
        <BarChartComp
          data={data}
          total={total}
          customization={p.customization}
        />
      )}

      {type === "pie" && (
        <PieChartComp
          data={data}
          total={total}
          customization={p.customization}
        />
      )}

      {type === "line" && (
        <LineChartComp
          data={data}
          total={total}
          customization={p.customization}
        />
      )}

      {visible && (
        <p className="w-full text-center text-sm mt-2 text-gray-400">
          Chart generated by Ventivo (https://ventivo.co)
        </p>
      )}
    </div>
  );
};

export default ChartComp;
