import Dashboard from "@/components/dashboard/dashboard";
import { BASE_URL, PAGES } from "@/constants/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard ~ Willow",
  description: "Generated by create next app", // Fix this
  openGraph: {
    title: "Dashboard ~ Willow",
    description: "Generated by create next app", // Fix this
    type: "website",
    url: BASE_URL + PAGES.dashboard, // Fix this
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Dashboard ~ Willow",
    description: "Generated by create next app",
    images: [
      {
        url: "", // Fix this
      },
    ],
  },
};

const Page = () => {
  return <Dashboard />;
};

export default Page;
