"use client";

// import type { Metadata } from "next";
import "../globals.css";
import { useEffect, useState } from "react";
import { redirect, useRouter } from "next/navigation";
import { PAGES } from "@/constants/constants";
import PageLoader from "@/components/general/page-loader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { getCustomer, getUserSession } from "@/lib/supabase";
import { RecoilRoot, useSetRecoilState } from "recoil";
import { customer_info, user_session } from "@/atoms/atoms";
import { AppSidebar } from "@/components/dashboard/app-sidebar";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

// export const metadata: Metadata = {
//   title: "Home ~ Valse",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: 5000,
    },
  },
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const setUserSession = useSetRecoilState(user_session);
  const setCustomerInfo = useSetRecoilState(customer_info);

  // useEffect(() => {
  //   (async () => {
  //     const { data } = await getUserSession();

  //     if (data.session === null) redirect(PAGES.login);
  //     else {
  //       const customer = await getCustomer(data.session.user.email as string);

  //       setCustomerInfo(customer);
  //       setUserSession(data.session);

  //       setLoading(false);
  //     }
  //   })();
  // }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <div className="[--header-height:calc(theme(spacing.14))] w-full">
        <SidebarProvider
          style={
            {
              "--sidebar-width": "19rem",
            } as React.CSSProperties
          }
        >
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator
                orientation="vertical"
                className="mr-2 data-[orientation=vertical]:h-4"
              />
              <Breadcrumb>
                <BreadcrumbList>
                  <BreadcrumbItem className="hidden md:block">
                    <BreadcrumbLink href="#">
                      Building Your Application
                    </BreadcrumbLink>
                  </BreadcrumbItem>
                  <BreadcrumbSeparator className="hidden md:block" />
                  <BreadcrumbItem>
                    <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                  </BreadcrumbItem>
                </BreadcrumbList>
              </Breadcrumb>
            </header>
            <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
              {children}
            </div>
          </SidebarInset>
        </SidebarProvider>
      </div>
    </QueryClientProvider>
  );
};

export default RootLayout;
