"use client";

// import type { Metadata } from "next";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/dashboard/site-header";
import { AppSidebar } from "@/components/dashboard/app-sidebar";
import { useEffect, useState } from "react";
import { redirect, useRouter } from "next/navigation";
import { PAGES } from "@/constants/constants";
import PageLoader from "@/components/general/page-loader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { getCustomer, getUserSession } from "@/lib/supabase";
import { RecoilRoot, useSetRecoilState } from "recoil";
import { customer_info, user_session } from "@/atoms/atoms";

// export const metadata: Metadata = {
//   title: "Home ~ Valse",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: 5000,
    },
  },
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const [loading, setLoading] = useState(true);
  const setUserSession = useSetRecoilState(user_session);
  const setCustomerInfo = useSetRecoilState(customer_info);

  useEffect(() => {
    (async () => {
      const { data } = await getUserSession();

      if (data.session === null) redirect(PAGES.login);
      else {
        const customer = await getCustomer(data.session.user.email as string);

        setCustomerInfo(customer);
        setUserSession(data.session);

        setLoading(false);
      }
    })();
  }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <div className="[--header-height:calc(theme(spacing.14))]">
        {loading ? (
          <PageLoader fullScreen />
        ) : (
          <SidebarProvider className="flex flex-col">
            <SiteHeader />
            <div className="flex flex-1 max-w-[1600px]">
              <AppSidebar />
              <SidebarInset>{children}</SidebarInset>
            </div>
          </SidebarProvider>
        )}
      </div>
    </QueryClientProvider>
  );
};

export default RootLayout;
